### ISSUE TITLE
[PE-D][Tester B] [edit] Wrong error message for negative integers

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W12-2/tp#111]
Input: edit -1 name/kda gives the wrong error message

![Wrong error message.png](https://raw.githubusercontent.com/jehousoh/ped/main/files/6871c439-cdb7-40c7-94a8-349b832aeefc.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: jehousoh/ped#2

**Comment by rui-han-crh** [comment]
Control flow:

1. Receive input
2. Check if input is parsable as an INTEGER
3. If so, parse input as an INDEX
4. If successful, carry on
5. Otherwise, throw index out of bounds (must be an integer lower than the lower bound)
6. From 2, otherwise, parse input as a STRING and use the `FindCommandParser` on this string
